server:
  port: 9090

spring:
  application:
    name: hxce-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hxce
    username: root
    password: abc123456
    hikari:
      pool-name: HikariCP
      minimum-idle: 8
      maximum-pool-size: 16
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      password: abc123456 # 修正缩进

  ai:
    deepseek:
      api-key: sk-6406fbb192d143caa8319996344fc411
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.ce_api.db.dao: warn

sa-token:
  # token名称
  token-name: token
  # token有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token最低活跃频率（单位：秒），如果token超过此时间没有访问系统就会被冻结，默认-1代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录（为true时允许一起登录, 为false时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token（为true时所有登录共用一个token, 为false时每次登录新建一个token）
  is-share: false
  # token风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false